# Generated by Django 4.2.3 on 2023-07-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='utl',
            field=models.CharField(blank=True, choices=[('PT', 'Python'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=4),
        ),
    ]
