# Generated by Django 4.2.3 on 2023-07-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_project_project_image_alter_project_utl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='utl',
            field=models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='utl1',
            field=models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='utl2',
            field=models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='utl3',
            field=models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='utl4',
            field=models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='utl5',
            field=models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='utl6',
            field=models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='utl7',
            field=models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20),
        ),
    ]
