# Generated by Django 4.2.3 on 2023-07-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_rename_utl_project_engine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Engine',
            new_name='Galia',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='utl1',
            new_name='Gamintojas',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='utl2',
            new_name='Marke',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='utl3',
            new_name='Spalva',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='utl4',
            new_name='Variklis',
        ),
    ]
