# Generated by Django 4.2.3 on 2023-08-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_alter_project_variklis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Marke',
            field=models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='Variklis',
            field=models.CharField(blank=True, choices=[('bak', 'bak')], max_length=20),
        ),
    ]
